CREATE TABLE TB_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) UNIQUE,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NAME VARCHAR2(20) NOT NULL
);

CREATE TABLE TB_TODOLIST(
	MEMBER_NO NUMBER CONSTRAINT FK_TB_TODOLIST REFERENCES TB_MEMBER(MEMBER_NO)
	ON DELETE CASCADE,
	TODO_NO NUMBER PRIMARY KEY,
	TODO_TITLE VARCHAR2(30) NOT NULL,
	TODO_DETAILS VARCHAR2(100) NOT NULL,
	TODO_STATUS CHAR(1) DEFAULT 'N' CONSTRAINT CHECK_TODO_STATUS CHECK(TODO_STATUS IN ('Y', 'N')),
	TODO_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TB_MEMBER;
SELECT * FROM TB_TODOLIST;
